name: Format, check, and test Slack App

on:
  workflow_call:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release run or not.

jobs:
  check-format-test-slack-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12', '3.13' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync
        run: |
          uv sync --all-extras --dev

      - name: Lint with Ruff
        run: |
          uv run ruff check

      - name: Type check with mypy
        run: |
          uv run mypy src tests

      - name: Test with pytest
        run: |
          uv run pytest tests/