name: On Merge Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-format-test:
    uses: ./.github/workflows/check-format-test.yml

  build-publish:
    needs: check-format-test
    uses: ./.github/workflows/build-publish.yml
